---
- name: PiNAS setup
  hosts: nas
  become: true

  roles:
    - { role: common, tags: common }
    - { role: argon-eon, tags: argon }
    - { role: wireguard, tags: wireguard }
    - { role: docker, tags: docker }
    - { role: lazydocker, tags: lazydocker }
    - { role: syncthing, tags: syncthing }
    - { role: raspi_reset, tags: raspi-reset }
    - { role: dotfiles, tags: dotfiles }
    # - { role: nextcloud, tags: nextcloud }

  pre_tasks:
    - { import_tasks: tasks/pinas/test.yml, tags: test }
    - { import_tasks: tasks/pinas/storage/main.yml, tags: storage }
    - { import_tasks: tasks/pinas/symlinks/main.yml, tags: symlinks }
    - { import_tasks: tasks/pinas/users/main.yml, tags: users }

  tasks:
    - { import_tasks: tasks/pinas/security/main.yml, tags: security }
    - { import_tasks: tasks/pinas/dns/main.yml, tags: dns }
    - { import_tasks: tasks/pinas/certbot/main.yml, tags: certbot }
    - { import_tasks: tasks/pinas/nginx/main.yml, tags: nginx }
    - { import_tasks: tasks/pinas/docker-containers/main.yml, tags: containers }
    - { import_tasks: tasks/pinas/playlist-sync/main.yml, tags: playlist-sync }
    - { import_tasks: tasks/pinas/samba/main.yml, tags: samba }
    - { import_tasks: tasks/pinas/scripts/main.yml, tags: scripts }

    - name: Add user {{ username }} to groups {{ ', '.join(user_groups + unix_groups | list) }}
      tags: groups
      user:
        name: "{{ username }}"
        groups: "{{ user_groups + unix_groups | list }}"
        append: yes
