---
- import_playbook: playbooks/common.yml
  tags: common
  vars:
    perform_full_upgrade: no
    install_common_tools: yes
    install_python_tools: yes
    install_media_tools: yes

- name: PiNAS setup
  hosts: nas
  become: true

  vars_files:
    - vars/main.yml
    - vars/users.yml
    - vars/storage.yml
    - vars/secrets.yml
    - vars/services.yml
    - vars/firewall.yml
    - vars/wg-peers.yml
    - vars/samba.yml

  roles:
    - { role: argon-eon, tags: argon }
    - { role: wireguard, tags: wireguard }
    - { role: docker, tags: docker }
    - { role: lazydocker, tags: lazydocker }
    - { role: syncthing, tags: syncthing }
    # - { role: nextcloud, tags: nextcloud }

  pre_tasks:
    - { import_tasks: tasks/test.yml, tags: test }
    - { import_tasks: tasks/storage/main.yml, tags: storage }
    - { import_tasks: tasks/symlinks/main.yml, tags: symlinks }
    - { import_tasks: tasks/raspi-reset/main.yml, tags: raspi-reset }
    - { import_tasks: tasks/users/main.yml, tags: users }

  tasks:
    - { import_tasks: tasks/security/main.yml, tags: security }
    - { import_tasks: tasks/dns/main.yml, tags: dns }
    - { import_tasks: tasks/certbot/main.yml, tags: certbot }
    - { import_tasks: tasks/nginx/main.yml, tags: nginx }
    - { import_tasks: tasks/docker-containers/main.yml, tags: containers }
    - { import_tasks: tasks/playlist-sync/main.yml, tags: playlist-sync }
    - { import_tasks: tasks/samba/main.yml, tags: samba }
    - { import_tasks: tasks/scripts/main.yml, tags: scripts }

    - name: Add user {{ username }} to groups {{ ', '.join(user_groups + unix_groups | list) }}
      tags: groups
      user:
        name: "{{ username }}"
        groups: "{{ user_groups + unix_groups | list }}"
        append: yes

- import_playbook: playbooks/user.yml
  tags: user
