---
- name: List containers and files
  set_fact:
    container_list: "{{ 'tasks/pinas/docker-containers/containers/*/docker-compose.yml' | fileglob | map('dirname') | map('basename') }}"
    container_dirs: >
      {{ lookup('filetree', 'tasks/pinas/docker-containers/containers', exclude='\.gitignore')
      | selectattr('state', 'equalto', 'directory')
      | map(attribute='path')
      | sort }}
    container_files: >
      {{ lookup('filetree', 'tasks/pinas/docker-containers/containers', exclude='\.gitignore')
      | selectattr('state', 'equalto', 'file')
      | map(attribute='path')
      | sort }}

- name: Create directory structure for compose files in /opt/docker-containers
  file:
    path: "/opt/docker-containers/{{ item }}"
    state: directory
  loop: "{{ container_dirs }}"

- name: Copy files for compose stacks to /opt/docker-containers
  template:
    src: "containers/{{ item }}"
    dest: "/opt/docker-containers/{{ item }}"
    owner: root
    group: docker
    mode: "{{ item.endswith('.env') | ternary('0640', '0644') }}"
  loop: "{{ container_files }}"

- name: Start containers
  command: docker compose --ansi never --progress plain up -d
  args:
    chdir: "/opt/docker-containers/{{ item }}"
  loop: "{{ container_list }}"
  register: _docker_compose_up
  changed_when: "'Started' in _docker_compose_up.stderr"
