entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /certs/letsencrypt.yml
      httpChallenge:
        entryPoint: web
