---
- name: List containers
  set_fact:
    container_list: "{{ 'tasks/docker-containers/containers/*/docker-compose.yml' | fileglob | map('dirname') | map('basename') }}"
    containers_with_env_file: "{{ 'tasks/docker-containers/containers/*/.env' | fileglob | map('dirname') | map('basename') }}"

- name: Create directories for compose files
  file:
    path: "/opt/docker-containers/{{ item }}"
    state: directory
  loop: "{{ container_list }}"
  # with_filetree: 'tasks/docker-containers/containers/'

- name: Copy compose files to /opt/docker-containers
  template:
    src: "containers/{{ item }}/docker-compose.yml"
    dest: "/opt/docker-containers/{{ item }}/docker-compose.yml"
    owner: root
    group: docker
    mode: 0640
  loop: "{{ container_list }}"

- name: Copy env files
  template:
    src: "containers/{{ item }}/.env"
    dest: "/opt/docker-containers/{{ item }}/.env"
    owner: root
    group: docker
    mode: 0640
  loop: "{{ container_list }}"
  when: item in containers_with_env_file

- name: Start containers
  command: docker compose --ansi never --progress plain up -d
  args:
    chdir: "/opt/docker-containers/{{ item }}"
  loop: "{{ container_list }}"
  register: _docker_compose_up
  changed_when: "'Started' in _docker_compose_up.stderr"
