---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    network_mode: host
    volumes:
      - /nas/appdata/uptime-kuma:/app/data
    environment:
      UPTIME_KUMA_HOST: 127.0.0.1
      UPTIME_KUMA_PORT: "{{ services['uptime-kuma'].port }}"
