---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - 127.0.0.1:{{ services.uptime_kuma.port }}:3001
    volumes:
      - /nas/appdata/uptime-kuma:/app/data
