---
services:
  vaultwarden: 
    subdomain: passwords
    port: 8080

  syncthing: 
    subdomain: syncthing
    port: 8384

  transmission: 
    subdomain: transmission
    port: 9091

  navidrome: 
    subdomain: music
    port: 4533

  ntfy:
    subdomain: ntfy
    port: 6666

  uptime-kuma:
    subdomain: uptime
    port: 3001

  immich:
    subdomain: photos
    port: 2283

  immich-power-tools:
    subdomain: immich-power-tools
    port: 8001

  pgadmin:
    subdomain: pgadmin
    port: 5050
