---
# - { import_tasks: tmpfs.yml, tags: tmpfs }
- { import_tasks: mdadm.yml, tags: mdadm }
- { import_tasks: zfs.yml, tags: zfs }
- { import_tasks: zfs-zed.yml, tags: zfs-zed }
- { import_tasks: sanoid/main.yml, tags: sanoid }

- name: Add mount points for hard drives
  mount:
    src: "{{ item.device }}"
    path: "{{ item.path }}"
    fstype: "{{ item.fs }}"
    state: mounted
  loop: "{{ disks }}"

- name: Add bind mounts
  tags: bind-mounts
  mount:
    src: "{{ item.src }}"
    path: "{{ item.mnt }}"
    opts: bind
    fstype: none
    state: mounted
  loop: "{{ bind_mounts }}"
