---
- name: Install certbot dependencies
  apt:
    name:
      - python3
      - python3-venv
      - libaugeas0
    state: present

- block:
    - name: Install certbot with pipx
      community.general.pipx:
        name: certbot
        state: present

    - name: Inject certbot-dns-infomaniak in certbot venv
      community.general.pipx:
        name: certbot
        state: inject
        inject_packages: certbot-dns-infomaniak

  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/sbin

- name: Save infomaniak token to /etc/letsencrypt/infomaniak.ini
  template:
    src: infomaniak.ini
    dest: /etc/letsencrypt/infomaniak.ini
    owner: root
    group: root
    mode: 0600

- name: Request certificates for domains
  command:
    cmd: >
      certbot certonly
        --non-interactive
        --agree-tos
        --preferred-challenges dns
        --authenticator dns-infomaniak
        --dns-infomaniak-credentials /etc/letsencrypt/infomaniak.ini
        --keep-until-expiring
        --cert-name "{{ main_domain }}"
        -d "{{ main_domain }}"
        -d "*.{{ main_domain }}"
  register: certbot_call
  changed_when: "'no action taken' not in certbot_call.stdout"

# --- Automatic renewal ---
- name: Install cron
  apt:
    name: cron
    state: present

- name: Enable cron service
  service:
    name: cron
    state: started
    enabled: yes

- name: Add cron job to renew certificates automatically
  cron:
    name: certbot-renew
    user: root
    special_time: daily
    job: /usr/local/sbin/certbot renew --quiet
    state: present    
    cron_file: certbot-renew
