---
- name: Install playlist-sync and scdl
  community.general.pipx:
    name: "{{ item }}"
    state: present
    install_deps: yes
    global: true
  loop:
    - playlist-sync
    - scdl

- name: Setup PATH and SHELL environment variables for cron jobs
  cron:
    user: "{{ username }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    env: yes
  loop:
    - name: PATH
      value: /usr/local/bin:/usr/bin:/bin
    - name: SHELL
      value: /bin/bash

- name: Add cron job to start playlist-sync and scdl at reboot
  cron:
    name: playlist-sync
    user: "{{ username }}"
    special_time: reboot
    job: tmux new-session -d -s playlist-sync "/nas/data/Music/sync.sh; bash; "
