---
- name: Install basic stuff and utilities
  hosts: all
  become: yes

  vars:
    perform_full_upgrade: no
    install_common_tools: yes
    install_python_tools: yes
    install_media_tools: no

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Full system upgrade
      apt:
        upgrade: full
      when: perform_full_upgrade
  
  tasks:
    - name: Install some utilities and command line tools
      apt:
        name:
          - bat
          - btop
          - command-not-found
          - cryptsetup
          - curl
          - fd-find
          - fish
          - git
          - htop
          - jq
          - lm-sensors
          - lsd
          - lshw
          - lsof
          - lvm2
          - ncdu
          - pv
          - python3
          - stow
          - tcpdump
          - tmux
          - tree
          - unzip
          - vim
          - wget
          - zsh
        state: present
      when: install_common_tools
      
    - name: Install pip, pipx and virtualenv
      apt:
        name:
          - python3-pip
          - python3-venv
          - python3-virtualenv
          - pipx
        state: present
      when: install_python_tools

    - name: Install some media tools
      apt:
        name:
          - ffmpeg
        state: present
        install_recommends: no
      when: install_media_tools
